<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" href="style/main.css" />
		<title>Редактирование таблицы на Perl, JavaScript</title>
		<meta name="ROBOTS" content="NOINDEX,NOFOLLOW,NOARCHIVE" />
        <link rel="shortcut icon" href="image/favicon2.ico" type="image/x-icon" />
	</head>
<body>
	<div class="center">

<h1><a href=".">Редактирование таблицы на Perl (на основе HTML 5, CSS 3.0 с применением JavaScript)</a></h1>